In [1]:
import numpy as np

In [2]:
a1 = np.arange(1, 11)
print(a1,'\n')

[ 1  2  3  4  5  6  7  8  9 10] 



In [3]:
a2 = np.zeros((3, 3))
print(a2, '\n')

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 



In [4]:
a3 = np.random.randint(1, 11, size=(5, 5))
print(a3, '\n')

[[ 6 10  4  7  5]
 [ 8  7  9 10  8]
 [ 9  8  7  6  1]
 [ 1  7  4  2  6]
 [ 2  5  7  8  6]] 



In [5]:
a4 = np.random.random((4, 4))
print(a4, '\n')

[[0.88690598 0.9174364  0.33452288 0.24900998]
 [0.71153931 0.41362234 0.46352604 0.38270852]
 [0.93635304 0.3515239  0.0037304  0.4962287 ]
 [0.67962449 0.38124976 0.38669614 0.07749901]] 



In [6]:
a5 = np.random.randint(1, 11, size=5)
a6 = np.random.randint(1, 11, size=5)

addition = a5 + a6
subtraction = a5 - a6
multiplication = a5 * a6

print("Масив 1:", a5)
print("Масив 2:", a6)
print("Додавання:", addition)
print("Віднімання:", subtraction)
print("Множення:", multiplication)

Масив 1: [1 5 7 8 9]
Масив 2: [4 8 2 8 1]
Додавання: [ 5 13  9 16 10]
Віднімання: [-3 -3  5  0  8]
Множення: [ 4 40 14 64  9]


In [7]:
a7=np.random.random(size=7)
a8=np.random.random(size=7)
print('\n', "Скалярний добуток 7 та 8 векторів:", np.dot(a7, a8))


 Скалярний добуток 7 та 8 векторів: 1.9424366311635413


In [8]:
a9 = np.random.randint(1, 11, size=(2, 2))
a10 = np.random.randint(1, 11, size=(2, 3))

print('Результат множення векторів:','\n',  np.dot(a9, a10),'\n')

Результат множення векторів: 
 [[ 33  62  58]
 [ 80 170 130]] 



In [9]:
a11 = np.random.randint(1, 11, size=(3, 3))

print('Матриця:','\n', a11, '\n')
print('Обернена матриця:','\n', np.linalg.inv(a11), '\n')

Матриця: 
 [[ 7  9  4]
 [ 7  8  8]
 [ 6 10  2]] 

Обернена матриця: 
 [[ 1.18518519 -0.40740741 -0.74074074]
 [-0.62962963  0.18518519  0.51851852]
 [-0.40740741  0.2962963   0.12962963]] 



In [10]:
a12 = np.random.random(size=(4, 4))

print('Матриця:','\n', a12, '\n')
print('Транспонована матриця:','\n', a12.T, '\n')

Матриця: 
 [[0.87950092 0.99831051 0.60793198 0.94679132]
 [0.3138978  0.54357244 0.01307669 0.0061431 ]
 [0.16352095 0.371289   0.37923343 0.81500573]
 [0.94208719 0.95075561 0.76420149 0.05013612]] 

Транспонована матриця: 
 [[0.87950092 0.3138978  0.16352095 0.94208719]
 [0.99831051 0.54357244 0.371289   0.95075561]
 [0.60793198 0.01307669 0.37923343 0.76420149]
 [0.94679132 0.0061431  0.81500573 0.05013612]] 



In [11]:
a12 = np.random.randint(1, 11, size=(3, 4))
a13 = np.random.randint(1, 11, size = 4)

print('Матриця: ','\n', a12, '\n')
print('Вектор: ', a13, '\n')
print('Результат множення матриці на вектор:','\n', np.dot(a12, a13), '\n')

Матриця:  
 [[5 7 2 2]
 [5 5 8 2]
 [2 9 4 2]] 

Вектор:  [8 3 1 1] 

Результат множення матриці на вектор: 
 [65 65 49] 



In [12]:
a14 = np.random.random(size=(3, 4))
a15 = np.random.random(size=4)

print('Матриця:','\n', a14, '\n')
print('Вектор:', a15, '\n')
print('Результат множення матриці на вектор:','\n', np.dot(a14,a15), '\n')

Матриця: 
 [[0.54963762 0.27179411 0.06847627 0.67234474]
 [0.69736998 0.38639156 0.23999564 0.61422358]
 [0.76623872 0.21627098 0.84711187 0.80987661]] 

Вектор: [0.99292085 0.45222992 0.92124525 0.06189481] 

Результат множення матриці на вектор: 
 [0.77335817 1.12628312 1.68914356] 



In [13]:
a16 = np.random.randint(1, 11, size=(2, 2))
a17 = np.random.randint(1, 11, size=(2, 2))

print('Матриця 1:','\n', a16, '\n')
print('Матриця 2:','\n', a17, '\n')
print('Результат поелементного множення матриць:','\n', a16*a17, '\n')

Матриця 1: 
 [[4 8]
 [5 5]] 

Матриця 2: 
 [[10  3]
 [ 7  4]] 

Результат поелементного множення матриць: 
 [[40 24]
 [35 20]] 



In [14]:
a18 = np.random.randint(1, 11, size = (2, 2))
a19 = np.random.randint(1, 11, size = (2, 2))

print('Матриця 1:','\n', a18, '\n')
print('Матриця 2:','\n', a19, '\n')
print('Добуток', '\n', np.dot(a18,a19), '\n')

Матриця 1: 
 [[3 8]
 [4 1]] 

Матриця 2: 
 [[5 1]
 [5 2]] 

Добуток 
 [[55 19]
 [25  6]] 



In [15]:
a20 = np.random.randint(1, 101, size = (5, 5))
print('Матриця:','\n', a20, '\n')
print('Сума всіх елементів елементів матриці:', np.sum(a20), '\n')

Матриця: 
 [[ 39  71  42   4 100]
 [ 68  90   1  42  76]
 [ 69  85  12  27   5]
 [ 78  74  53  50  21]
 [ 29  26  84  45  77]] 

Сума всіх елементів елементів матриці: 1268 



In [16]:
a21 = np.random.randint(1, 11, size = (4,4))
a22 = np.random.randint(1, 11, size = (4,4))

print('Матриця 1:','\n', a21, '\n')
print('Матриця 2:','\n', a22, '\n')
print('Різниця матриць:','\n', a21-a22, '\n')

Матриця 1: 
 [[ 3  6  2  3]
 [10  3  4  9]
 [ 8  9  4 10]
 [ 1  9  6  7]] 

Матриця 2: 
 [[ 3  3  4  5]
 [ 8  5  7 10]
 [ 5  2  2  3]
 [10 10 10  5]] 

Різниця матриць: 
 [[ 0  3 -2 -2]
 [ 2 -2 -3 -1]
 [ 3  7  2  7]
 [-9 -1 -4  2]] 



In [17]:
a23 = np.random.random(size = (3,3))
print('Матриця:','\n', a23, '\n')
print('Сума елементів у кожному рядку:', np.sum(a23, axis=1))

Матриця: 
 [[0.93374027 0.08453698 0.93937389]
 [0.58160413 0.89654218 0.42273716]
 [0.30580116 0.31667281 0.22028026]] 

Сума елементів у кожному рядку: [1.95765114 1.90088348 0.84275424]


In [18]:
a24 = np.random.randint(1, 11, size = (3,4))
print('Матриця:','\n', a24, '\n')
print('Ця матриця з числами у квадраті', '\n', a24**2, '\n')

Матриця: 
 [[ 1  1  4  1]
 [ 2  5  9  3]
 [ 8  5  2 10]] 

Ця матриця з числами у квадраті 
 [[  1   1  16   1]
 [  4  25  81   9]
 [ 64  25   4 100]] 



In [19]:
a25 = np.random.randint(1, 51, size=4)
print('Вектор:', a25, '\n')
print('Квадратний корень цього вектора:', np.sqrt(a25))

Вектор: [28  7  2 47] 

Квадратний корень цього вектора: [5.29150262 2.64575131 1.41421356 6.8556546 ]
